<?php
/**
 * @file
 * @author Shea McKinney <sheamck@stanford.edu>
 * Provides the ability to offer several layouts on the home page via context.
 * Provides a dashboard administrative page to toggle through those layouts
 *
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function stanford_jumpstart_home_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
}

/**
 * Implements hook_help().
 */
function stanford_jumpstart_home_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    /*
     *case 'admin/help#block':
     *  return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href="@blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.', array('@blocks' => url('admin/structure/block'))) . '</p>';
     */
    case 'admin/stanford-jumpstart-home':
      return '<p>' . t('For more help please contact %sws', array('%sws' => l('Stanford Web Services', 'mailto:sitesjumpstart-help@lists.stanford.edu'))) . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function stanford_jumpstart_home_permission() {
  return array(
    /*
     *'administer my module' =>  array(
     *  'title' => t('Administer my module'),
     *  'description' => t('Perform administration tasks for my module.'),
     *),
     */
    'administer stanford homepage' =>  array(
      'title' => t('Administer Stanford Homepage'),
      'description' => t('Allow user to change and modify the homepage settings'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function stanford_jumpstart_home_menu() {
  /*
   *$items['blog'] = array(
   *  'title' => 'blogs',
   *  'page callback' => 'blog_page',
   *  'access arguments' => array('access content'),
   *  'type' => MENU_SUGGESTED_ITEM,
   *);
   */
  $items['admin/config/stanford/homepage'] = array(
    'title' => 'Homepage Dashboard',
    'page callback' => 'stanford_jumpstart_home_dashboard',
    'access arguments' => array('administer stanford homepage'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * The dashboard functionality for the home page.
 * @return [type] [description]
 */
function stanford_jumpstart_home_dashboard() {
  $output = "";
  drupal_set_title('Customize your homepage');

  $output .= drupal_render(drupal_get_form('stanford_jumpstart_homepage_dashboard_form'));

  return $output;
}

/**
 * Implements hook_context_default_contexts().
 */
function stanford_jumpstart_home_context_default_contexts() {
  $export = stanford_jumpstart_home_get_contexts();

  if (empty($export)) {
    return array();
  }

  return $export;
}

/**
 * Loads up and returns all contexts that are in the layouts folder.
 * @return [type] [description]
 */
function stanford_jumpstart_home_get_contexts($clear_cache = FALSE) {

  // cache_set($cid, $data, $bin = 'cache', $expire = CACHE_PERMANENT);
  // cache_get($cid, $bin = 'cache');
  // cache_clear_all($cid = NULL, $bin = NULL, $wildcard = FALSE)

  $cache = cache_get('jumpstart_home_context');
  $contexts = array();

  if (!$clear_cache && is_object($cache) && !isset($cache->data[''])) {
    $contexts = $cache->data;
  }
  else {
    $dir = drupal_get_path('module', 'stanford_jumpstart_home') . '/layouts';
    $mask = "/.*\.inc$/";
    $options['key'] = 'name';
    $files = file_scan_directory($dir, $mask, $options);

    foreach ($files as $name => $data) {
      require_once DRUPAL_ROOT . "/" . $data->uri;
      $contexts[$context->name] = $context;
    }

  }

  cache_set('jumpstart_home_context', $contexts);

  return $contexts;
}

/**
 * [stanford_jumpstart_homepage_dashboard_form description]
 * @param  [type] $form       [description]
 * @param  [type] $form_state [description]
 * @return [type]             [description]
 */
function stanford_jumpstart_homepage_dashboard_form($form, $form_state) {

  $filename = drupal_get_path('module', 'stanford_jumpstart_home') . "/stanford_jumpstart_home.info";
  $info = drupal_parse_info_file($filename);
  $layouts = $info['layout'];

  foreach ($layouts as $key => $config) {
    $context = context_load($config['context']);

    // Field Group
    $form[$key] = array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array(
          'homepage-layout',
        ),
      ),
    );

    // Move the selected option to the top of the pile!
    if (!$context->disabled) {
      $form[$key]['#weight'] = -10;
    }

    // Thumbnail
    $img_path = drupal_get_path('module', 'stanford_jumpstart_home') . "/img/" . $config['thumb'];
    $variables = array(
      'path' => $img_path,
      'alt' => $config['title'],
      'title' => $config['title'],
    );
    $form[$key]['thumb']["#markup"] = theme_image($variables);

    // Enabled
    $class = ($context->disabled) ? "" : "selected";
    $form[$key]['status']['#markup'] = "<div><a class=\"$class button\" name=\"". $context->name . "\" id=\"" . $context->name . "\">" . (($context->disabled) ? t("Select") : t("Selected")) . "</a></div>";

    // Title
    $form[$key]['title']['#markup'] = "<h2 class=\"title\">" . t($config['title']) . "</h2>";

    // Description
    $form[$key]['description']['#markup'] = check_markup($config['description'], 'filtered_html');

    // Background Image Field
    if (!empty($config['background_image'])) {
      $form[$key]['background_image'] = array(
        '#title' => t('Background Image'),
        '#type' => 'managed_file',
        '#description' => t('The uploaded image will be displayed on this layout as a background image.'),
        '#default_value' => variable_get('stanford_jumpstart_home_' . $config['context'] . '_background', ''),
        '#upload_location' => 'public://stanford_jumpstart_home/background/',
      );
    }

    // Header Image Field
    if (!empty($config['header_image'])) {
      $form[$key]['header_image'] = array(
        '#title' => t('Header Image'),
        '#type' => 'managed_file',
        '#description' => t('The uploaded image will be displayed on this layout as a header image.'),
        '#default_value' => variable_get('stanford_jumpstart_home_' . $config['context'] . '_header', ''),
        '#upload_location' => 'public://stanford_jumpstart_home/header/',
      );
    }

    // Color picker
    if (!empty($config['color'])) {
      $form[$key]['color'] = array(
        '#title' => t('Choose Color'),
        '#type' => 'select',
        '#description' => t('Choose the color you would like your background to be.'),
        '#options' => array(
          '#FF00FF' => t('Supa Pink'),
          '#00FF00' => t('Supa Green'),
          '#000000' => t('black'),
        ),
      );
    }

  }

  $form['submit'] = array('#type' => 'submit', '#value' => t('Save homepage settings'));

  return $form;
}
