<?php
/**
 * @file
 * @author Shea McKinney <sheamck@stanford.edu>
 * Provides the ability to offer several layouts on the home page via context.
 * Provides a dashboard administrative page to toggle through those layouts
 *
 */

/**
 * Implements hook_help().
 */
function stanford_jumpstart_home_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    /*
     *case 'admin/help#block':
     *  return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href="@blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.', array('@blocks' => url('admin/structure/block'))) . '</p>';
     */
    case 'admin/stanford-jumpstart-home':
      return '<p>' . t('For more help please contact %sws', array('%sws' => l('Stanford Web Services', 'mailto:sitesjumpstart-help@lists.stanford.edu'))) . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function stanford_jumpstart_home_permission() {
  return array(
    /*
     *'administer my module' =>  array(
     *  'title' => t('Administer my module'),
     *  'description' => t('Perform administration tasks for my module.'),
     *),
     */
    'administer stanford homepage' =>  array(
      'title' => t('Administer Stanford Homepage'),
      'description' => t('Allow user to change and modify the homepage settings'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function stanford_jumpstart_home_menu() {
  /*
   *$items['blog'] = array(
   *  'title' => 'blogs',
   *  'page callback' => 'blog_page',
   *  'access arguments' => array('access content'),
   *  'type' => MENU_SUGGESTED_ITEM,
   *);
   */
  $items['admin/config/stanford/homepage'] = array(
    'title' => 'Homepage Dashboard',
    'page callback' => 'stanford_jumpstart_home_dashboard',
    'access arguments' => array('administer stanford homepage'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * The dashboard functionality for the home page.
 * @return [type] [description]
 */
function stanford_jumpstart_home_dashboard() {
  $output = "<p>Please create this functionality</p>";

  return $output;
}
