<?php
/**
 * @file
 * @author Shea McKinney <sheamck@stanford.edu>
 * Provides the ability to offer several layouts on the home page via context.
 * Provides a dashboard administrative page to toggle through those layouts
 *
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function stanford_jumpstart_home_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
}

/**
 * Implements hook_help().
 */
function stanford_jumpstart_home_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    /*
     *case 'admin/help#block':
     *  return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href="@blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.', array('@blocks' => url('admin/structure/block'))) . '</p>';
     */
    case 'admin/stanford-jumpstart-home':
      return '<p>' . t('For more help please contact %sws', array('%sws' => l('Stanford Web Services', 'mailto:sitesjumpstart-help@lists.stanford.edu'))) . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function stanford_jumpstart_home_permission() {
  return array(
    /*
     *'administer my module' =>  array(
     *  'title' => t('Administer my module'),
     *  'description' => t('Perform administration tasks for my module.'),
     *),
     */
    'administer stanford homepage' =>  array(
      'title' => t('Administer Stanford Homepage'),
      'description' => t('Allow user to change and modify the homepage settings'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function stanford_jumpstart_home_menu() {
  /*
   *$items['blog'] = array(
   *  'title' => 'blogs',
   *  'page callback' => 'blog_page',
   *  'access arguments' => array('access content'),
   *  'type' => MENU_SUGGESTED_ITEM,
   *);
   */
  $items['admin/config/stanford/homepage'] = array(
    'title' => 'Homepage Dashboard',
    'page callback' => 'stanford_jumpstart_home_dashboard',
    'access arguments' => array('administer stanford homepage'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * The dashboard functionality for the home page.
 * @return [type] [description]
 */
function stanford_jumpstart_home_dashboard() {
  $output = "<p>Please create this functionality</p>";

  return $output;
}

/**
 * Implements hook_context_default_contexts().
 */
function stanford_jumpstart_home_context_default_contexts() {
  $export = stanford_jumpstart_home_get_contexts();

  if (empty($export)) {
    return array();
  }

  return $export;
}

/**
 * Loads up and returns all contexts that are in the layouts folder.
 * @return [type] [description]
 */
function stanford_jumpstart_home_get_contexts($clear_cache = FALSE) {

  // cache_set($cid, $data, $bin = 'cache', $expire = CACHE_PERMANENT);
  // cache_get($cid, $bin = 'cache');
  // cache_clear_all($cid = NULL, $bin = NULL, $wildcard = FALSE)

  $cache = cache_get('jumpstart_home_context');
  $contexts = array();

  if (!$clear_cache && is_object($cache) && !isset($cache->data[''])) {
    $contexts = $cache->data;
  }
  else {
    $dir = drupal_get_path('module', 'stanford_jumpstart_home') . '/layouts';
    $mask = "/.*\.inc$/";
    $options['key'] = 'name';
    $files = file_scan_directory($dir, $mask, $options);

    foreach ($files as $name => $data) {
      require_once DRUPAL_ROOT . "/" . $data->uri;
      $contexts[$context->name] = $context;
    }

  }

  cache_set('jumpstart_home_context', $contexts);

  return $contexts;
}
